apiVersion: v1
kind: Service
metadata:
  name: telnyx-sip-service
  labels:
    app: telnyx-sip
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: telnyx-sip