name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ferchomap/telnyx-sip-server:latest,ferchomap/telnyx-sip-server:${{ github.sha }}
    
    - name: Set up kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    - name: Create k8s secret
      run: |
        cat << EOF > secret.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          name: telnyx-sip-secrets
        type: Opaque
        stringData:
          TELNYX_API_KEY: ${{ secrets.TELNYX_API_KEY }}
          TELNYX_CONNECTION_ID: ${{ secrets.TELNYX_CONNECTION_ID }}
          TELNYX_FROM_NUMBER: ${{ secrets.TELNYX_FROM_NUMBER }}
          TELNYX_VOICE_APP_ID: ${{ secrets.TELNYX_VOICE_APP_ID }}
          TELNYX_OUTBOUND_PROFILE: ${{ secrets.TELNYX_OUTBOUND_PROFILE }}
          SIP_USERNAME: ${{ secrets.SIP_USERNAME }}
          SIP_PASSWORD: ${{ secrets.SIP_PASSWORD }}
          SIP_SERVER: ${{ secrets.SIP_SERVER }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          NUMERO_SOPORTE: ${{ secrets.NUMERO_SOPORTE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        EOF
        kubectl apply -f secret.yaml
        rm secret.yaml
    
    - name: Update deployment image
      run: |
        kubectl set image deployment/telnyx-sip-server telnyx-sip-server=ferchomap/telnyx-sip-server:${{ github.sha }}
    
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/telnyx-sip-server